name: Refresh roster daily
on:
  schedule:
    - cron: '0 9 * * *'   # daily 09:00 UTC
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    permissions:
      contents: write
    env:
    LETTERS: "i"
      ACTIVE_YEARS: "3"
      MIN_BOUTS: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python full_roster_scraper.py
      - name: Commit updated roster
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/roster.csv
          git commit -m "Update roster.csv [skip ci]" || echo "No changes"
          git push
